name: Test Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    env:
      CI: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Restore dependencies
      run: npm install
      working-directory: ./ClientApp

    - name: Build
      run:  dotnet build || true
      continue-on-error: true